from PIL import Image, ImageDraw, ImageFont
import os

def generate_infographic(stock_list, filename="stock_infographic.png"):
    """
    Generates a simple infographic image listing the top stocks.
    stock_list: List of strings (e.g., stock names or titles)
    """
    width = 800
    height = 1000
    background_color = (20, 20, 30)  # Dark Blue/Black
    text_color = (255, 255, 255)
    accent_color = (0, 255, 150)     # Neon Green
    
    # Create image
    img = Image.new('RGB', (width, height), color=background_color)
    draw = ImageDraw.Draw(img)
    
    # Try to load a font, fallback to default if not found
    try:
        # Common Windows fonts
        title_font = ImageFont.truetype("arialbd.ttf", 60)
        item_font = ImageFont.truetype("arial.ttf", 30)
    except IOError:
        title_font = ImageFont.load_default()
        item_font = ImageFont.load_default()

    # Draw Header
    draw.text((50, 50), "TOP INDIAN STOCKS", font=title_font, fill=accent_color)
    draw.text((50, 120), "WEEKLY INSIGHTS", font=item_font, fill=text_color)
    
    # Draw Divider
    draw.line((50, 170, 750, 170), fill=accent_color, width=3)
    
    # Draw Items
    y_position = 220
    for idx, item in enumerate(stock_list[:10]):  # Limit to top 10
        # Truncate if too long to fit roughly
        display_text = f"{idx + 1}. {item}"
        if len(display_text) > 50:
             display_text = display_text[:47] + "..."
             
        draw.text((50, y_position), display_text, font=item_font, fill=text_color)
        y_position += 60
        
    # Draw Footer
    draw.text((50, height - 80), "Generated by Nano Banan Automation", font=item_font, fill=(150, 150, 150))

    img.save(filename)
    print(f"Infographic saved to {filename}")
    return filename

if __name__ == "__main__":
    # Test
    test_data = ["Tata Motors", "Reliance Industries", "HDFC Bank", "Infosys", "ITC", "SBI", "Bajaj Finance", "TCS", "Adani Enterprises", "Maruti Suzuki"]
    generate_infographic(test_data)
